@baseUrl = http://localhost:5122

### Obtener todos los boards
GET {{baseUrl}}/api/boards

### Crear un board
POST {{baseUrl}}/api/boards
Content-Type: application/json

{
  "title": "Mi primer board",
  "description": "Board de prueba",
  "ownerId": "00000000-0000-0000-0000-000000000001"
}